### PR TITLE
Updates Plugins to take advantage of Neovim 0.5.0

### PR DESCRIPTION
**Pull request by qxjit**
This updates a number of plugins to take advantage of Neovim 0.5.0
advancements:

* Neovim 0.5.0 has native LSP support. This commit replaces coc.vim with plugins
  to use this native support, with a change to how per-project settings
  are configured. Now projects provide a custom wrapper script to launch
  the Haskell Language Server in the correct way for that project.

  I have not tested it, but I believe Neovim 0.5.0 supports running
  multiple Haskell language servers for different projects.

* Adds CtrlSF to recover a similar "search and replace" functionality
  that Coc.vim was providing.

* Replaces CtrlP with Telescope, which uses fancy Neovim features to
  provide rich popup for finding files and previewing them. We can
  always go back to CtrlP if we decide we don't like this.

### CODE REVIEW

**Comment by jbrechtel** [comment]
No hiccups for me so far. I'll try the LSP stuff in a bit though.

**Comment by qxjit** [comment]
@jbrechtel For references, here's what a working per-project wrapper script using docker looks like:

```
#!/bin/sh

exec docker-compose \
  -f docker-compose.dev.yml \
  run --rm -T \
  docker-service-name stack exec \
  haskell-language-server-wrapper -- "$@"
```

Obviously this needs HLS installed on the image for the container that it runs.

**Review by jbrechtel — APPROVED** [review]
:+1: This all works without problems for me.

The fuzzy finder seems to have at least some of the same shortcomings that CtrlP had* but the much taller list mitigates any downsides a lot. Most of the time it's great anyway.

LSP support seems to work really well, too.

* - The problem I'm referencing is where searches like "Service.hs" will match a directory with "Service" in the name and a file ending in .hs but with a different name before matching "Service.hs" itself. CtrlP was genuinely broken in these scenarios because you couldn't even find the correct match in its truncated list. With Telescope I can usually see it but always scroll to it, at least.

**Comment by jbrechtel** [comment]
Oh I also tried the search and replace and it worked fine for me.

**Pull request merged**
